// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdutygaynjfebhuyxulm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdXR5Z2F5bmpmZWJodXl4dWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIzNDEyNTEsImV4cCI6MjA5NzkxNzI1MX0.3B2_xfhEhAHl6pYd0Wij-QQToX3Dw7n3v2H8dBoXOuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});